export const LOAD_QUESTION = 'LOAD_QUESTION'
export const LOAD_QUESTIONS_SUCCESSFULL = 'LOAD_QUESTIONS_SUCCESSFULL'
export const RECIEVE_QUESTIONS = 'RECIEVE_QUESTIONS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'